[project]
name = "agents-playground"
version = "0.1.0"
description = "Agents Playground — Google ADK (for now), extensible later"
authors = [
    { name = "Pavel Krusek", email = "pavel@krusek.dk" }
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "google-adk (>=1.18.0,<2.0.0)",
    "google-genai (>=1.49.0,<2.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "rich (>=14.2.0,<15.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "typer (>=0.20.0,<0.21.0)"
]

[project.urls]
Homepage = "https://github.com/pavelkrusek/agents-playground.git"
Repository = "https://github.com/pavelkrusek/agents-playground.git"

[tool.poetry.scripts]
adkp = "adk_playground.cli:app"
agents = "adk_playground.cli:app"

[tool.poetry]
packages = [{ include = "adk_playground", from = "src" }]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
